# Generated by Django 4.2.2 on 2023-06-09 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0003_alter_car_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='description',
            field=models.TextField(default=''),
        ),
    ]
