# Generated by Django 4.2.2 on 2023-06-09 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0004_car_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='description',
            field=models.TextField(default='Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce gravida malesuada varius. Nullam eget nulla tristique, consequat urna nec, auctor justo. Quisque semper magna a feugiat fringilla. Sed id semper mauris, nec consectetur nisi. Pellentesque fringilla, ex at venenatis rutrum, justo urna elementum purus, eget lobortis justo risus vel nisi. Curabitur sollicitudin metus nec justo facilisis tempus. Aliquam vitae ligula nec massa tristique pharetra. Maecenas eget diam sed orci sagittis scelerisque ut eu augue. Integer vestibulum risus sit amet consectetur finibus. Sed eu turpis justo. Sed feugiat, erat ac suscipit pellentesque, mauris dui facilisis mauris, nec pharetra velit velit vitae tellus. Nulla tempus, felis sit amet efficitur pulvinar, odio erat tristique felis, ut vulputate nisi enim vel nisl. Sed et felis et ante hendrerit cursus. Aenean consectetur sapien at convallis varius. Sed in neque aliquet, consectetur lorem sit amet, interdum diam. Morbi dignissim eros eget orci accumsan, a aliquam risus luctus. Donec lobortis auctor diam ut facilisis.'),
        ),
    ]
