# Generated by Django 4.2.2 on 2023-06-09 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0006_description_remove_car_description_car_descriptions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='descriptions',
        ),
        migrations.AddField(
            model_name='car',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.DeleteModel(
            name='Description',
        ),
    ]
