# Generated by Django 4.2.2 on 2023-06-09 01:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0007_remove_car_descriptions_car_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='description',
        ),
    ]
