# Generated by Django 4.2.2 on 2023-06-09 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0008_remove_car_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Descripcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='car',
            name='descriptions',
            field=models.ManyToManyField(to='cars.descripcion'),
        ),
    ]
