# Generated by Django 4.2.2 on 2023-06-09 01:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0009_descripcion_car_descriptions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='descriptions',
        ),
        migrations.AddField(
            model_name='descripcion',
            name='car',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='descriptions', to='cars.car'),
            preserve_default=False,
        ),
    ]
