# Generated by Django 4.2.2 on 2023-06-09 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0010_remove_car_descriptions_descripcion_car'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.DeleteModel(
            name='Descripcion',
        ),
    ]
