# Generated by Django 4.2.2 on 2023-06-09 02:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0012_remove_car_description_ficha'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='car_ficha',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='related_car', to='cars.ficha'),
        ),
        migrations.AlterField(
            model_name='ficha',
            name='carro',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='related_ficha', to='cars.car'),
        ),
    ]
