# Generated by Django 4.2.2 on 2023-06-09 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0013_car_car_ficha_alter_ficha_carro'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='car_ficha',
        ),
        migrations.AddField(
            model_name='car',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.DeleteModel(
            name='Ficha',
        ),
    ]
