# Generated by Django 4.2.2 on 2023-06-09 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0015_description_remove_car_description_car_descriptions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='descriptions',
            field=models.ManyToManyField(blank=True, to='cars.description'),
        ),
    ]
