# Generated by Django 4.2.2 on 2023-06-09 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0017_remove_car_descriptions_description_car'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='model',
            field=models.PositiveIntegerField(),
        ),
    ]
