# Generated by Django 4.2.2 on 2023-06-09 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0019_rename_model_car_model_year_alter_car_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='model_year',
        ),
        migrations.AddField(
            model_name='car',
            name='model',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='car',
            name='price',
            field=models.CharField(max_length=100),
        ),
    ]
