# Generated by Django 4.2.2 on 2023-06-09 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0020_remove_car_model_year_car_model_alter_car_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='model',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='car',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
