# Generated by Django 4.2.2 on 2023-06-09 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0023_remove_car_model_car_model_year_alter_car_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='model_year',
            field=models.PositiveIntegerField(),
        ),
    ]
