# Generated by Django 4.2.2 on 2023-06-12 02:42

import cars.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0030_alter_car_model_alter_car_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='model',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='car',
            name='price',
            field=models.CharField(max_length=100, validators=[cars.models.validate_price]),
        ),
    ]
