# Generated by Django 4.2.2 on 2023-06-16 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0031_alter_car_model_alter_car_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='model',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='car',
            name='price',
            field=models.CharField(max_length=100),
        ),
    ]
